# Copyright (c) SIPist Development Team
# Distributed under the terms of the Modified BSD License.
services:
  notebook:
    container_name: notebook
    restart: unless-stopped
    image: ghcr.io/sipist/notebook:2025-10-06
    volumes:
      - ./.ir_datasets:/home/jovyan/.ir_datasets
      - ./work:/home/jovyan/work
      - ./data:/home/jovyan/data
      - ./images:/home/jovyan/images
    environment:
      - JUPYTER_PORT=10000
    ports:
      - 10000:10000
    networks:
      - sipist-workspace-network

networks:
  sipist-workspace-network:
    driver: bridge
