# Copyright (c) SIPist Development Team
# Distributed under the terms of the Modified BSD License.
services:
  dns-cache:
    restart: unless-stopped
    image: coredns/coredns:latest
    command:
      - -conf
      - /etc/coredns/Corefile
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 9.9.9.9
    volumes:
      - ./coredns/Corefile:/etc/coredns/Corefile:ro
    expose:
      - "9153"
    networks:
      sipist-workspace-network:
        ipv4_address: 172.28.0.53

  notebook:
    container_name: notebook
    restart: unless-stopped
    image: ghcr.io/sipist/notebook:edge
    depends_on:
      - dns-cache
    volumes:
      - ./.ir_datasets:/home/jovyan/.ir_datasets
      - ./work:/home/jovyan/work
      - ../ir-labs/data:/home/jovyan/data
      - ../ir-labs/labs:/home/jovyan/labs
      - ../ir-labs/project:/home/jovyan/project
    environment:
      - JUPYTER_PORT=10000
    dns:
      - 172.28.0.53
    ports:
      - 10000:10000
    networks:
      - sipist-workspace-network

networks:
  sipist-workspace-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
